@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu May 09 12:44:50 +0300 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto feffc16750b5468d996f062d07dcc2c0 --incr --debug typical --relax --mt 2 -L secureip -L xpm --snapshot design_2_wrapper_behav xil_defaultlib.design_2_wrapper -log elaborate.log"
call xelab  -wto feffc16750b5468d996f062d07dcc2c0 --incr --debug typical --relax --mt 2 -L secureip -L xpm --snapshot design_2_wrapper_behav xil_defaultlib.design_2_wrapper -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
